core/src/main/java/com/googlecode/psiprobe/beans/ResourceResolverBean.java
As described in tomcat [GlobalNamingResources](http://tomcat.apache.org/tomcat-7.0-doc/config/globalresources.html) docs, "resources defined in this element are <b>not</b> visible in the per-web-application contexts unless you explicitly link them with <ResourceLink> elements".
Tomcat's new behavior is actually the right one. I tried to track the tomcat svn commit that change it, without success. Later I check how Tomcat configure the JNDI and how the lookup are done. It binds the web application JNDI Context to the web application classloader, while the Global Resources are listed in the Common Classloader.
This fix consist of changing the current thread classloader during the lookup to the common classloader and later change it back to the original web classloader.
=> Fixed #411 Tomcat 7.0.54 Psi probe not listing global datasource

core/src/main/java/com/googlecode/psiprobe/AbstractTomcatContainer.java, core/src/main/java/com/googlecode/psiprobe/beans/JBossResourceResolverBean.java, core/src/main/java/com/googlecode/psiprobe/beans/ResourceResolver.java, core/src/main/java/com/googlecode/psiprobe/beans/ResourceResolverBean.java, core/src/main/java/com/googlecode/psiprobe/controllers/datasources/ResetDataSourceController.java, core/src/main/java/com/googlecode/psiprobe/controllers/sql/ConnectionTestController.java, core/src/main/java/com/googlecode/psiprobe/controllers/sql/ExecuteSqlController.java, tomcat80adaptor/src/main/java/com/googlecode/psiprobe/Tomcat80ContainerAdaptor.java
Just put together all changes from pull request https://github.com/psi-probe/psi-probe/pull/465 into my master branch.
This fixes probe not listing global and application resources in Tomcat 8 while preserving Java 1.4 compatibility.
Tested on RHEL 7, Server JRE 1.8.0_40, Tomcat 8.0.21 and Probe 2.4.0-SNAPSHOT.
=> Update #394 Tomcat 8 Psi probe not listing global and application datasources

pom.xml
IDE plugin for intellij is retired for a long time now.  Eclipse plugin
is going to be updated to maven 2.2.1 then it is likely headed to
retirement as well.  Both IDE's provide support beyond what these
plugins could provide natively.  Eclipse uses m2e.  Idea uses their own.
=> Remove IDE plugins - no longer necessary

pom.xml
log4j 1.2.17 still targets java 1.4 making this a compliant update for psi-probe 2.4.
=> Updated log4j to avoid exclusions

core/src/test/java/com/googlecode/psiprobe/beans/stats/listeners/FlapListenerTests.java, core/src/test/java/com/googlecode/psiprobe/beans/stats/listeners/ThresholdListenerTests.java, core/src/test/java/com/googlecode/psiprobe/tools/InstrumentsTests.java, core/src/test/java/com/googlecode/psiprobe/tools/SizeExpressionTests.java, core/src/test/java/com/googlecode/psiprobe/tools/WhoisTests.java, pom.xml
Per #453, this library is using maven 3.  Therefore, it can use the latest compiler.  Additionally, this opens the door to continue compiling source/target for 1.4 java while treating test as source/target 1.5.  This allows for the library to be upgraded to junit 4.12 through a bit of maven magic.  This does not affect the outcome of the build itself and still is compliant for java 1.4.  All JVMs used to build are 1.6 and above which means this is suitable for inclusion into the build process even with psi-probe 2.4.0.
=> Junit 4.12

.travis.yml, README.md, pom.xml, web/pom.xml
JTA 1.1 can be used directly from maven central and still targets java 1.4
Added openjdk7 to travis ci build
Added user group to README
Fixed formatting in POM from a prior change (excess tabs).
=> Use JTA 1.1 plus minor project changes

core/src/main/java/com/googlecode/psiprobe/beans/LogResolverBean.java, core/src/main/java/com/googlecode/psiprobe/controllers/logs/ChangeLogLevelController.java, core/src/main/java/com/googlecode/psiprobe/tools/logging/tomcatSlf4jLogback/TomcatSlf4jLogbackAppenderAccessor.java, core/src/main/java/com/googlecode/psiprobe/tools/logging/tomcatSlf4jLogback/TomcatSlf4jLogbackFactoryAccessor.java, core/src/main/java/com/googlecode/psiprobe/tools/logging/tomcatSlf4jLogback/TomcatSlf4jLogbackLoggerAccessor.java
Tomcat-slf4j-logback project replaces tomcat juli with slf4j/logback. See [here](https://github.com/grgrzybek/tomcat-slf4j-logback)
This results in inability for psi-probe to see those logs.  This change
treats the logs similar to logback and thus makes them available and
accessible.
=> TomcatSlf4jLogback Support

pom.xml
Update project pom to include reporting plugins for mvn site.
Don't ask how the extra spaces in the <project> tag got added. I can't seem to undo it in IntelliJ.  
Disabled org.owasp:dependency-check-maven as it causes builds to be long. We can think about adding it for releases or as something optional when we start updating artifacts to latest versions.
=> Update project pom to include reporting plugins for mvn site.

tomcat55adaptor/pom.xml, tomcat60adaptor/pom.xml, tomcat70adaptor/pom.xml, tomcat80adaptor/pom.xml
This has been sitting a bit on my machine...
Align poms for tomcat so they are fairly close to being the same.  Update to latest tomcat 7 and just one behind on tomcat 8.  Effectively not much going on here.
On jsp pages, language tag is obsolete and otherwise ignored.  Cleared all the warnings.  Again effectively not much going on here.
=> Align tomcat poms 5, 6, 7, 8

.gitignore, tomcat55adaptor/pom.xml, tomcat60adaptor/pom.xml, tomcat70adaptor/pom.xml, tomcat80adaptor/pom.xml
Fix scope of artifacts to be able to run the project in Intellij IDEA.
While setup project in Intellij IDEA 14, I noticed that you are unable to run the project in Tomcat.
Reason for this is the clash of libraries. All Tomcat specific artifacts must have scope provided, otherwise they are deployed.
=> - Fixes #529  dependency scope optimizations

tomcat60adaptor/src/main/java/com/googlecode/psiprobe/Tomcat60ContainerAdaptor.java, tomcat70adaptor/src/main/java/com/googlecode/psiprobe/Tomcat70ContainerAdaptor.java
Fixes #531.
The `AbstractTomcatContainer.bindToContext` and `unbindToContext` implementation doesn't work because it pass null to token.
I override both methods on Tomcat60ContainerAdaptor and Tomcat70ContainerAdaptor to pass the apropriate expected value.
I have test this on Tomcat 6 (Java 5 and 6) and on Tomcat 7 (Java 6), but I believe it will work on Java 7 and 8. I will test it on the next days.
=> Fix listing global/application datasources on Tomcat 6 and 7

tomcat80adaptor/pom.xml, tomcat80adaptor/src/main/java/com/googlecode/psiprobe/beans/Tomcat8DbcpDatasourceAccessor.java, web/src/main/webapp/WEB-INF/spring-probe-resources.xml
Fixes #534 Psi probe not listing global/application datasources on Tomcat 8.
=> Fix listing global/application datasources on Tomcat8

tomcat70adaptor/src/main/java/com/googlecode/psiprobe/Tomcat70ContainerAdaptor.java, tomcat80adaptor/src/main/java/com/googlecode/psiprobe/Tomcat80ContainerAdaptor.java
This was done to enable the tab Applications, System Information etc to show up, as the probe was
unable to identify the Pivotal server.
=> Adding the support for Pivotal tc servers. 

core/src/main/java/com/googlecode/psiprobe/beans/stats/collectors/AppStatsCollectorBean.java, pom.xml, web/src/main/webapp/WEB-INF/spring-probe-controllers.xml, web/src/main/webapp/WEB-INF/spring-probe-resources.xml, web/src/main/webapp/WEB-INF/spring-probe-security.xml, web/src/main/webapp/WEB-INF/spring-probe-servlet.xml, web/src/main/webapp/WEB-INF/spring-probe-stats.xml
This pull request will bring the library up to spring 4.  It is dependent on #379 occurring first.  Therefore it's build on top of that pull request.  Spring 4 required quartz 2.x.  So what I would like to do here is wait until the quartz piece is merged before this is then merged.
What is absent in this upgrade is dealing with spring security.
This partially fixes #449 
This patch also brings spring security 3.2.x up to the latest.
Again, hold off merging this until after #379 is merged.  Once that is merged this one is ready to be merged.  If it doens't drop the commits off here I can resubmit it shortly after to ensure we only show exactly what is changing here.
=> Spring4 - partial

README.md
Fixes #570 by adding visibility to version eyes to project.  Additionally added coveralls badge and notes regarding requirement to build with jdk7.
=> New Badges and JDK 7 Build Notes - Fixes #570

core/pom.xml, pom.xml
Bring all libraries up to latest support to resolve version eyes reporting including 5 vulnerabilities now listed on master README badge for versioneyes.
Fixes #581
=> Full jdk6 library support - Fixes #581

core/pom.xml, pom.xml, tomcat70adapter/pom.xml
Java mail doesn't come with tomcat so usage of it requires we utilize
the implementation and api not just the api.
This fixes #587
=> Per Sonar analysis, add missing libraries and correct java mail usage - Fixes #587

pom.xml
Fixes #585 
We are still targetting java 6 on our builds.  This is for git commit id plugin, coveralls, and checkstyles.  Each now require java 7 and otherwise do not affect our outcome.  These additionally, go towards making version eyes see the library as up to date.
=> Update maven plugins and dependencies to java 7 - Fixes #585

core/src/main/java/com/googlecode/psiprobe/beans/stats/providers/MultipleSeriesProvider.java, core/src/main/java/com/googlecode/psiprobe/tools/AsyncSocketFactory.java, core/src/main/java/com/googlecode/psiprobe/tools/Whois.java
Use package protected properties that are used by inner classes.
=> Java Language Cleanups - Use package protected properties

core/src/main/java/com/googlecode/psiprobe/AbstractTomcatContainer.java, core/src/main/java/com/googlecode/psiprobe/beans/stats/collectors/AbstractStatsCollectorBean.java, core/src/main/java/com/googlecode/psiprobe/beans/stats/listeners/MemoryPoolMailingListener.java, core/src/main/java/com/googlecode/psiprobe/beans/stats/listeners/StatsCollectionEvent.java, core/src/main/java/com/googlecode/psiprobe/model/IpInfo.java, core/src/main/java/com/googlecode/psiprobe/model/sql/DataSourceTestInfo.java, core/src/main/java/com/googlecode/psiprobe/tokenizer/StringTokenizer.java, core/src/main/java/com/googlecode/psiprobe/tools/AccessorFactory.java, core/src/main/java/com/googlecode/psiprobe/tools/SecurityUtils.java, core/src/main/java/com/googlecode/psiprobe/tools/TimeoutException.java, core/src/main/java/com/googlecode/psiprobe/tools/logging/DefaultAccessor.java, core/src/main/java/com/googlecode/psiprobe/tools/logging/jdk/Jdk14ManagerAccessor.java, core/src/main/java/com/googlecode/psiprobe/tools/logging/log4j/Log4JManagerAccessor.java, core/src/main/java/com/googlecode/psiprobe/tools/logging/logback/LogbackFactoryAccessor.java, core/src/main/java/com/googlecode/psiprobe/tools/logging/slf4jlogback/TomcatSlf4jLogbackFactoryAccessor.java
Prevent Synthetic Accessor by adding constructor
Add empty arrays as [0] instead of [] {} for example new URL[0] instead of new URL[] {}
Remove Unnecessary constructors
Comment required contructors where constructors are overridden
=> Java Language Cleanups - Micro Updates

core/src/main/java/com/googlecode/psiprobe/Utils.java, core/src/main/java/com/googlecode/psiprobe/jsp/AddQueryParamTag.java, core/src/main/java/com/googlecode/psiprobe/jsp/ParamToggleTag.java, core/src/main/java/com/googlecode/psiprobe/jsp/VisualScoreTag.java, core/src/test/java/com/googlecode/psiprobe/jsp/VisualScoreTagTest.java
Use StringBuilder() instead of StringBuffer().  It is not possible everywhere as some are improperly used at class level and thus require synchronization.  Therefore remaining ones will be addressed later by changing their usage to be more in line with modern java practice.
=> Java Language Cleanups - Use StringBuilder rather than StringBuffer

pom.xml
This partially fixes issue #593.  In doing so jacoco is intended initially just for sonar usage so it immiately activates since sonar is by default build using jacoco.
=> [jacoco] Add jacoco for sonarqube support - Fixes #593

core/pom.xml, core/src/test/java/com/googlecode/psiprobe/LogbackConfigTest.java, pom.xml
It excludes slf4j-jdk14 from openejb and create a test to make sure slf4j-jdk14 is no more on the classpath.
=> Fixes #620 Class path contains multiple SLF4J bindings.

core/pom.xml, pom.xml
The included one was 12 years old, was causing errors in eclipse with
usage in Jboss resolver, and disabling included one which was completely
modernized and had more features.  Using legacy one would have limited
us going forwards.
Fixes #615
=> Remove JMX as it is provided by Java SE since 5.0 - Fixes #615

tomcat70adapter/src/main/java/com/googlecode/psiprobe/Tomcat70ContainerAdapter.java
Remove support for tomcat 7.0.15 as that poses security risk in general usage and assumes we are supporting that version of tomcat.  This fixes issue #616
=> Remove tomcat 7.0.15 and lower support - Fixes #616

web/src/main/webapp/WEB-INF/spring-probe-security.xml
Fixes #634 by replacing path-type with request-matcher which is further documented in xsd.
=> Spring fix deprecated path-type by changing to request-matcher - Fixes #634

core/pom.xml, pom.xml, tomcat70adapter/pom.xml, tomcat80adapter/pom.xml, tomcat90adapter/pom.xml
Fixes #632 
- Remove unnecessary dependencies from adapters
- Exclude commons-logging in parent not core
=> Maven POM Cleanup - Fixes #632

pom.xml, web/src/main/webapp/WEB-INF/spring-probe-security.xml
Previously 'sif' bean was disabled.  Discovered it's replacement that was for spring security 3+.  Also removed previously commented out elements as no constructors existed any longer and we have been running ok for some time without those settings. 
This finalizes #449
=> Upgraded spring security 3 to 4 and turned 'sif' back on

core/src/main/java/psiprobe/beans/LogResolverBean.java, core/src/main/java/psiprobe/beans/ResourceResolverBean.java, core/src/main/java/psiprobe/jsp/VisualScoreTag.java, core/src/main/java/psiprobe/tools/JmxTools.java, core/src/main/java/psiprobe/tools/Mailer.java, core/src/main/java/psiprobe/tools/logging/catalina/CatalinaLoggerAccessor.java
This pull request is focused on resolving occurrences of Sonar rule squid:UselessParenthesesCheck - Useless parentheses around expressions should be removed to prevent any misunderstanding.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AUselessParenthesesCheck
Please let me know if you have any questions.
George Kankava
=> squid:UselessParenthesesCheck - Useless parentheses around expressions should be removed to prevent any misunderstanding

core/src/main/java/psiprobe/controllers/apps/AjaxToggleContextController.java
org.apache.catalina.Context.getAvailable() were deprecated in Tomcat 7
and a note were added stating it will be removed in Tomcat 8. Therefore,
the java.lang.NoSuchMethodError at
org.apache.catalina.Context.getAvailable().
=> Fixes #573 Error stopping/starting an app with Probe 2.4 under Tomcat 8

core/pom.xml, core/src/main/java/psiprobe/controllers/logs/FollowController.java, core/src/main/java/psiprobe/model/DisconnectedLogDestination.java, core/src/main/java/psiprobe/tools/logging/AbstractLogDestination.java, core/src/main/java/psiprobe/tools/logging/LogDestination.java, core/src/main/java/psiprobe/tools/logging/logback/LogbackAppenderAccessor.java
Fixes #644.
This actually will only work for logback loggers. We could create one issue for each logging API.
=> FollowController always open log files with system charset encoding

web/pom.xml
After logback.xml was moved into standard location, the filtering necessary to indicate where logs land no longer was activated by default.  Adjusted the pom so this picks up properly.  Now logging is back to normal.
=> Must filter logback resource due to moving it's location

core/src/main/java/psiprobe/AbstractTomcatContainer.java, core/src/main/java/psiprobe/ProbeServlet.java, core/src/main/java/psiprobe/controllers/ContextHandlerController.java, core/src/main/java/psiprobe/controllers/RenderChartController.java, core/src/main/java/psiprobe/controllers/TomcatContainerController.java, core/src/main/java/psiprobe/controllers/WhoisController.java, core/src/main/java/psiprobe/controllers/apps/AjaxReloadContextController.java, core/src/main/java/psiprobe/controllers/apps/AjaxToggleContextController.java, core/src/main/java/psiprobe/controllers/apps/NoSelfContextHandlerController.java, core/src/main/java/psiprobe/controllers/deploy/UndeployContextController.java, core/src/main/java/psiprobe/controllers/deploy/UploadWarController.java, core/src/main/java/psiprobe/controllers/sql/CachedRecordSetController.java, core/src/main/java/psiprobe/controllers/sql/QueryHistoryItemController.java, core/src/main/java/psiprobe/controllers/system/AdviseGarbageCollectionController.java, core/src/main/java/psiprobe/controllers/threads/GetClassLoaderUrlsController.java, core/src/main/java/psiprobe/controllers/wrapper/RestartJvmController.java, core/src/main/java/psiprobe/controllers/wrapper/StopJvmController.java, core/src/main/java/psiprobe/controllers/wrapper/ThreadDumpController.java, core/src/main/java/psiprobe/controllers/wrapper/WrapperInfoController.java
Some loggers atributes were added in classes that don't use it. The
reason is to prevent usage of Spring super classes protected logger
atribute.
@hazendaz can you check if the line endings problem is occurring?
=> Replaces Commons Logging usage with Slf4j - Fixes #613

web/src/main/webapp/WEB-INF/web.xml
Reverts fd71e53be09084565f30bb9b6354fa6fd1c3c7d1
Addresses issue caused by #594 with tomcat handling of secure cookie and usage of spring in regardes to http processing.  While we ultimately want this, rather than full revert, this is a comment with description that issue is created.
=> Reverts fd71e53 Disable secure-cookie until issues with spring can be determined under http usage

core/src/main/java/psiprobe/AbstractTomcatContainer.java, core/src/main/java/psiprobe/TomcatContainer.java, core/src/main/java/psiprobe/beans/LogResolverBean.java
getContainerWrapper().getTomcatContainer().getLogger(context) does
nothing more than context.getLogger().  It's cleaner to just grab logger
directly.  In this case, logger is treated as Object in each case as
usage within method expects Object so the logic there stays as-is.
This was likely a legacy usage in older tomcats which changed over time to no longer be tied to tomcat directly.
=> Remove wrapped method calls to simply get logger out of original passed context

web/src/main/webapp/WEB-INF/web.xml
Default JESSIONID will show in URL.  This setting for servlet 3.0+ stops presenting the JSESSIONID in the URL.  This is considered a security fix.
=> Change cookie tracking-mode to COOKIE so it's not in the URL

core/pom.xml, pom.xml, web/pom.xml
slf4j to 1.7.18
logback to 1.1.6
missed tomcat 7 to 7.0.68
remove jaxen as it is not used
=> Update more versions and remove jaxen

core/pom.xml, pom.xml, rest/pom.xml, tomcat70adapter/pom.xml, tomcat80adapter/pom.xml, tomcat90adapter/pom.xml, web/pom.xml
=> Correct SCM Urls

pom.xml, web/pom.xml
In order to get off some legacy slf4j dependencies in our builds, I tracked down displaytag and ported from svn to git and released it to central.  This includes many changes over last 7 years since last release from original authors.  Additionally, it has internally been updated to latest & greatest.  Continued support for displaytag will now reside [here](https://github.com/hazendaz/displaytag).
Enjoy!
=> Update to displaytag 2.0.2 from hazendaz

web/src/main/webapp/WEB-INF/jsp/attributes.jsp
Currently, the session expire link will fail as the web-app parameter is missing. By using the ${param.webapp} the missing parameter will be added the the link will work.
=> Fixed session expire link by using the web-app parameter

README.md, pom.xml, src/site/site.xml
Update all the dependencies, upgrade site to use more https, and revert slf4j/logback due to outstanding issues with newer versions we have not addressed yet.
=> Update dependencies and revert slf4j/logback

web/src/main/webapp/WEB-INF/jsp/ajax/appRuntimeInfo.jsp, web/src/main/webapp/WEB-INF/jsp/ajax/cluster/members.jsp, web/src/main/webapp/WEB-INF/jsp/ajax/memory_pools.jsp, web/src/main/webapp/WEB-INF/jsp/ajax/servlets.jsp, web/src/main/webapp/WEB-INF/jsp/ajax/sql/connection.jsp, web/src/main/webapp/WEB-INF/jsp/appattributes.jsp, web/src/main/webapp/WEB-INF/jsp/appfiltermaps.jsp, web/src/main/webapp/WEB-INF/jsp/appfilters.jsp, web/src/main/webapp/WEB-INF/jsp/appinitparams.jsp, web/src/main/webapp/WEB-INF/jsp/applications.jsp, web/src/main/webapp/WEB-INF/jsp/attributes.jsp, web/src/main/webapp/WEB-INF/jsp/certificates_table.jsp, web/src/main/webapp/WEB-INF/jsp/connectors.jsp, web/src/main/webapp/WEB-INF/jsp/datasourcegroup.jsp, web/src/main/webapp/WEB-INF/jsp/datasources_table.jsp, web/src/main/webapp/WEB-INF/jsp/datasourcetest.jsp, web/src/main/webapp/WEB-INF/jsp/follow.jsp, web/src/main/webapp/WEB-INF/jsp/logs.jsp, web/src/main/webapp/WEB-INF/jsp/resources.jsp, web/src/main/webapp/WEB-INF/jsp/servletmaps.jsp, web/src/main/webapp/WEB-INF/jsp/sessions.jsp, web/src/main/webapp/WEB-INF/jsp/showjsps.jsp, web/src/main/webapp/WEB-INF/jsp/sysinfo.jsp, web/src/main/webapp/WEB-INF/jsp/threadpools.jsp, web/src/main/webapp/WEB-INF/jsp/threads.jsp, web/src/main/webapp/WEB-INF/jsp/threads_sun.jsp, web/src/main/webapp/WEB-INF/jsp/view_jsp_source.jsp, web/src/main/webapp/WEB-INF/jsp/view_servlet_source.jsp, web/src/main/webapp/WEB-INF/jsp/view_xml_conf.jsp
Previously discussed via #725.  Due to lack of available time, leaving this as is as it clears all warnings produced in modern IDE checks.  It's more important at this point to adhere to standards rather than deprecated settings in html specs.  Will spin back to this when we have time and issue is being raised for future addressing.  At that time, we should address CSS entirely.
=> html updates for html5

pom.xml
I have figured out issue with prototype being incorrectly configured in many cases where it should have been using GET.  As that will take more time to look and and correct, for now reverting back to 4.2.6 so users can continue working with library.
=> [pom] Revert spring to 4.2.6 until we can figure out issue with 4.3.x

pom.xml, web/src/main/webapp/WEB-INF/jsp/appsummary.jsp, web/src/main/webapp/WEB-INF/jsp/cluster.jsp, web/src/main/webapp/WEB-INF/jsp/follow.jsp, web/src/main/webapp/WEB-INF/jsp/memory.jsp, web/src/main/webapp/WEB-INF/jsp/servlets.jsp
One tag issue had wrong property value and prototype was configured to use post where get should have been used.  This caused the 405 errors users exprienced when tryinging to upgrade to spring 4.3.1.  Now we are going back to 4.3.1 and it's working.  Fixes #754
=> [pom] Upgrade to spring 4.3.1 and fix prototype/tagging issues

core/src/main/java/psiprobe/controllers/deploy/UploadWarController.java, core/src/main/java/psiprobe/controllers/jsp/RecompileJspController.java, core/src/main/java/psiprobe/controllers/jsp/ViewSourceController.java, core/src/main/java/psiprobe/controllers/sessions/ListSessionsController.java, core/src/main/java/psiprobe/controllers/sql/ExecuteSqlController.java, web/src/main/webapp/WEB-INF/spring-probe-security.xml
By default, we should not be allow random creation of session.  When we tried in the past to further secure the application we ran into issues with excess session creation.  This was part of the issue but not the full story.  This however is enough to ensure that if a session expires it isn't simply restored which could be sign of a security issue.
=> Attempt to prevent unexpected session creation

docs/logback-samples/sift-appender/README.md, docs/logback-samples/sift-appender/logback.xml
New directory called 'docs' with samples of items we might use for testing various scenerios.  First up the SIFT appender support I last used to get SIFT support fixed.  Worth keeping for reference.
=> Add SIFT logback.xml for support of testing our SIFT logback logic

pom.xml
We don't need two coverage libraries.  While I've been unable to figure out how to get aggregate setup locally it doesn't matter for sonar.  When we push to sonar, it aggregates automatically.  Otherwise tests are just at the various projects when running the site page.
=> [coverage] Cleanup jacoco setup and remove cobertura 

core/src/main/java/psiprobe/tools/logging/logback/LogbackLoggerAccessor.java, core/src/main/java/psiprobe/tools/logging/slf4jlogback/TomcatSlf4jLogbackLoggerAccessor.java, pom.xml
Fixes #720 
Issue was not so much with us using newer logback as that worked fine but rather if user misconfigures logback to be at a version higher than slf4j within their war.  That would cause this issue reported originally in #719.  After much testing, it did not matter if psi probe and tomcat-juli versions were newer.  It seemed to simply be setting slf4j-api to older than 1.7.14 and logback newer than 1.1.5 (there abouts).  Anyway, this fix will simply allow logs to still display that can be understood and a log will be written with the stack trace plus a note to upgrade slf4j to 1.7.21 or better.  Effectively this is better and no worse than all the X number of logs we already don't show.  I don't see any other real way to address this and at this point, I'd rather push people …
=> Slf4j/Logback Upgrade plus code fix - Fixes #720

web/src/main/webapp/WEB-INF/jsp/decorators/probe.jsp, web/src/main/webapp/WEB-INF/jsp/follow.jsp, web/src/main/webapp/WEB-INF/spring-probe-controllers.xml
Preparing for switching to spring annotations.  There is a conflict using 'index.htm' in this way.  After review, 'list' makes the most sense so switching it.
=> [logs] Rename '/logs/index.htm' to '/logs/list.htm'

core/src/main/java/psiprobe/controllers/logs/AbstractLogHandlerController.java, core/src/main/java/psiprobe/controllers/logs/ChangeLogLevelController.java, core/src/main/java/psiprobe/controllers/logs/DownloadLogController.java, core/src/main/java/psiprobe/controllers/logs/FollowController.java, core/src/main/java/psiprobe/controllers/logs/FollowedFileInfoController.java, core/src/test/java/psiprobe/controllers/logs/LogHandlerControllerTest.java, web/src/main/webapp/WEB-INF/spring-probe-controllers.xml
prep work for annotation based spring.  We need to move away from sharing objects which makes code mush more clear.
=> [controller] Abstract LogHandlerController and separate followedFileInfo object

core/src/main/java/psiprobe/beans/ResourceResolverBean.java, web/src/main/webapp/WEB-INF/spring-probe-resources.xml
When switching to spring annotations, we cannot have circular logic (ie
core requiring the tomcat modules).  Therefore, switching this to string
based so it ports with all working as expected.
=> [spring] Switch datasource accessor to string based due to separation of tomcat needs

core/src/main/java/psiprobe/controllers/sql/ConnectionTestController.java
This was commented out.  No history explains why.  It works so added it back.
=> [jdbc] Uncomment check on jdbc version

web/src/main/webapp/WEB-INF/jboss-web.xml
Version 6 was called 3.0 for a while thus naming we still have.  Schema
looks like it was 6 right away as it was the web profile of jbossAS 6.
=> [jboss] Replace JBOSS DTD with jboss-web 6.0 xsd since we support 6 / 7

core/src/main/java/psiprobe/tools/ApplicationUtils.java
A lot of classes with getInfo() defined in tomcat are being removed.  The reason is that since java 5, java has had available Class().getSimpleName() which is equivalent for the most part.  So for tomcat 7, still trying the old way since I got that going but for all remaining versions simply grabbing the simple class name.
=> [sbean] Add session solution using class simpleName going forwards for tomcat 8+

web/src/main/webapp/WEB-INF/jsp/ajax/cluster/requests.jsp, web/src/main/webapp/WEB-INF/jsp/ajax/cluster/traffic.jsp, web/src/main/webapp/WEB-INF/jsp/ajax/follow.jsp, web/src/main/webapp/WEB-INF/jsp/ajax/followed_file_info.jsp, web/src/main/webapp/WEB-INF/jsp/ajax/osinfo.jsp, web/src/main/webapp/WEB-INF/jsp/ajax/sql/connection.jsp, web/src/main/webapp/WEB-INF/jsp/certificates.jsp, web/src/main/webapp/WEB-INF/jsp/certificates_table.jsp, web/src/main/webapp/WEB-INF/jsp/connectors.jsp, web/src/main/webapp/WEB-INF/jsp/datasources.jsp, web/src/main/webapp/WEB-INF/jsp/datasourcetest.jsp, web/src/main/webapp/WEB-INF/jsp/errors/paramerror.jsp, web/src/main/webapp/WEB-INF/jsp/errors/serverversion.jsp, web/src/main/webapp/WEB-INF/jsp/memory.jsp, web/src/main/webapp/WEB-INF/jsp/servlets.jsp, web/src/main/webapp/WEB-INF/jsp/showjsps.jsp, web/src/main/webapp/WEB-INF/jsp/sysinfo.jsp
certain taglibs not used on the jsp pages themselves are not necessary and only confuse usage.
=> [jsp] Remove unnecessary taglibs

core/src/main/java/psiprobe/beans/BoneCpDatasourceAccessor.java
This will fix the error but doesn't likely fix overall issue.  Will request community feedback.  Will close out issue otherwise as it's now null protected.
=> [pool] Add patch to boneCp in case pool returns null which is allowed - Fixes #405

core/src/main/java/psiprobe/AbstractTomcatContainer.java
Fix context in safe context location
ROOT##1 style is treated differently with tomcat.  Our code was adding /ROOT##1 throughout.  While it lands on disk that way, tomcat doesn't see it that way.  It's really ##1.  So while it appeared issue was fixed for non ROOT usage, it was always broken for root usage.  Now it works for ROOT usage as well as normal usage.  ROOT entries will simply show as ##1 rather than ROOT##1 as on disk.
Entirely fixed best I can tell.  Please review and let me know if there are any concerns about where I fixed this.  Seems like all is ok but might want a little more testing tomorrow just to confirm no down side.
=> [context] For parallel deployment of ROOT - Fixes #545

web/src/main/resources/logback.xml
Note that logback still spits out the error as they internally used deprecated class.  This has been fixed [here](https://github.com/qos-ch/logback/commit/39c7ab9510c4f48ef3fcbef248aac380d3b58235).  No idea when this will be released.  New style is for 1.1.7 and 1.1.8 logback which applies to our 1.1.8 usage.  Warning will go away upon next logback release.
=> [logback] Update deprecated rollingpolicy

core/src/main/java/psiprobe/controllers/certificates/ListCertificatesController.java, core/src/main/java/psiprobe/controllers/certificates/SSLHostConfigHelper.java, pom.xml
Changes to support SSLHostConfig broke backwards compatability.  This is a partial fix.  Tomcat 7/8 will not show certificate at the moment but will startup again.  The issue was that spring failed due to imports of SSLHostConfig that are not present in tomcat 7/8.  By retooling that spring will be ok but we are still not showing certs for tomcat 7/8 at the moment.
=> Split out SSLHostConfig and use reflection so tomcat 7/8 startup

core/src/main/java/psiprobe/jsp/VisualScoreTag.java
Trying to wrap this way will close the output and cause exception and
inibility to startup.
=> [leak] Restore JspWriter outside try / catch as it is not a leak

core/src/main/java/psiprobe/beans/ResourceResolverBean.java, core/src/main/java/psiprobe/controllers/certificates/ListCertificatesController.java, core/src/main/java/psiprobe/model/certificates/OldConnectorInfo.java
We needed null checks in case only truststore or keystore is used.  This logic matched original and applies in both original and new.  Also, we didn't need to replace ConnectorInfo but rather just use proper fields as the remainder will then read it as expected.
=> Cleanup certificate information

core/src/main/java/psiprobe/controllers/certificates/ListCertificatesController.java
Why because type is not required and is defaulted later so that is a bad
check.  while keystore gets set elsewhere truststore does not and will
eventually get whatever keystore has so it's best to check that we are
pointed to a file.
=> [certs] Patch null check with check on file instead

.travis.yml, README.md, core/pom.xml, ojdbc7-pom.xml, pom.xml, travis/after_success.sh, travis/script.sh, travis/settings.xml, ucp-pom.xml
In 2016, Oracle opened up allowing their maven repository to be used for
building both locally and on build systems.  Due to break in our builds
as old method now fails us, this has been fully setup.  For any
individual contributors wanting to work with psi-probe, instructions
have been added to direct them to setup.
=> [oracle] Attach to oracle maven repository

web/pom.xml
Property for tomcat is default.  Leave it as such.  If running as jboss,
it will automatically override that setting.  This gets rid of
activeByDefault so we can use more profiles.
=> [ci] Remove another case of unnecessary profile

core/pom.xml, core/src/main/java/psiprobe/controllers/deploy/CopySingleFileController.java, core/src/main/java/psiprobe/controllers/deploy/UploadWarController.java, pom.xml
After all, we are using tomcat and it comes with this baked in.
=> [ci] Use internal commons fileupload instead of separate copy

core/src/main/java/psiprobe/ProbeConfig.java, pom.xml
quartz 2.3.0 has removed their update check so this setting can now be
removed.
fixes #1053
=> [quartz] Remove obsolete skipUpdateCheck - fixes #1053

pom.xml
I am currently the lead on spotbugs maven plugin.  In turn, it leads back to findbugs maven plugin.  Good work is applying to both now and given the high level of bugs in this project, it makes sense to use this as a model for working with both.  Or better stated this is my test project of findbugs/spotbugs usage until such time we address the total overall issues which is well over 300+.
=> Update spring, add back findbugs, and update plugins around that

.travis.yml, pom.xml, web/pom.xml
jspc -> Not even sure why original was even used as it was not compiling so unsure what it's purpose was.  I think it should have compiled to confirm code was good then dumped the compilation.  Anyway, this will now compile the jsp into a directory in target 'jspc' and then will simply not pick it up for distribution.
Remainder brought up to java 9 build support.  For build related items like the jetty piece I'm going to have to rework a bit to allow further upgrades but think we might drop java 7 soon as it's becoming too complicated to keep supporting the past and with nearly a million downloads a release building on java 9 is a good point to just start diverging from that past.
=> All things java 9 now building

core/src/main/java/psiprobe/controllers/BeanToXmlController.java, core/src/main/java/psiprobe/model/stats/StatsCollection.java
warnings don't seem to go away and I am not seeing any issues.  this is essentially what is suggested as the fix so publishing in case someone else can provide further insite.
=> [secure] Add suggestions for Xstream to secure usage

pom.xml
we were using 8.5.  While we support all currently supported, our core can safely move to 9.0.8 as we are on java 8 now.
=> [pom] Update base tomcat to 9.0.8

web/src/main/webapp/WEB-INF/jsp/appattributes.jsp, web/src/main/webapp/WEB-INF/jsp/appfiltermaps.jsp, web/src/main/webapp/WEB-INF/jsp/appfilters.jsp, web/src/main/webapp/WEB-INF/jsp/appinitparams.jsp, web/src/main/webapp/WEB-INF/jsp/appsummary.jsp, web/src/main/webapp/WEB-INF/jsp/datasourcetest.jsp, web/src/main/webapp/WEB-INF/jsp/decorators/application.jsp, web/src/main/webapp/WEB-INF/jsp/resources.jsp, web/src/main/webapp/WEB-INF/jsp/servletmaps.jsp, web/src/main/webapp/WEB-INF/jsp/servlets.jsp, web/src/main/webapp/WEB-INF/jsp/sessions.jsp, web/src/main/webapp/WEB-INF/jsp/showjsps.jsp, web/src/main/webapp/WEB-INF/jsp/view_jsp_source.jsp, web/src/main/webapp/WEB-INF/jsp/view_xml_conf.jsp
param.webapp is the name of the webapp.  This comes from server not client but nvs cannot figure that out.  Unless user can inject into parameters which is already blocked, this should not be a problem.  However, to ensure we make nvs trust our usage, this causes no degrade in how things work.
=> [secure] Per nvs, add htmlEscape to param usage

core/src/main/java/psiprobe/tools/logging/log4j2/Log4J2AppenderAccessor.java
This one supresses thrown exception into a less likely method call and is preferred over using invoke method.
=> [log4j2] Change invokemethod to get property

core/src/main/java/psiprobe/model/stats/StatsCollection.java
This will reduce failures seen in logs since it did not check before performing action previously and would fail under a number of conditions.
=> [stats] Add better protection around stats collection deletions/renaming

pom.xml, tomcat70adapter/pom.xml, tomcat80adapter/pom.xml, tomcat85adapter/pom.xml, tomcat90adapter/pom.xml
core works fine with the upgrade but the adapters do not.  For those, drop back to 1.47 for time being.
=> Partial jmockit 1.48 Update

core/src/main/java/psiprobe/controllers/RenderChartController.java, core/src/main/java/psiprobe/jfreechart/Effect3D.java, core/src/main/java/psiprobe/jfreechart/XYLine3DRenderer.java, core/src/main/java/psiprobe/jfreechart/package-info.java, pom.xml
Jfreechart dropped the emulated 3D support.  In order to be up-to-date and retain compatibility, a new package to restore support with jfreechart has been added to psi probe.
=> [jfree] Upgrade to jfreechart 1.5.0 retaining 3D support

tomcat70adapter/src/main/java/psiprobe/Tomcat70ContainerAdapter.java, tomcat70adapter/src/test/java/psiprobe/Tomcat70ContainerAdapterTest.java
jboss does not support this release any longer, it's long vulnerable and we are not going to support it either.
=> [remove] Drop support for jboss web 7.0

core/pom.xml, web/src/main/webapp/META-INF/context.xml
quartz introduced this even though we don't need it via quartz currently.  It was also on an old copy and possibly what is causing users issues accessing their dbs.
=> Remove transient hikaricp from build output

.mvn/settings.xml
- github may not be needed here
- older gh-pages was wrong but also likely not needed now
- gh-pages-scm is handled via scm and probably not needed
=> [settings] Adjust settings to match up with usage

psi-probe-core/src/main/java/psiprobe/model/stats/StatsCollection.java
NullPointerException introduced by 184ce97331e21ed5aa7b4870b5ba1a09daf04f30
The problem is, that the exception message `does not "opens java.util" to unnamed module` is not set at the ExceptionInInitializerError itself, but at the nested InaccessibleObjectException. The ExceptionInInitializerError has no message at all, which causes the NullPointerException.
With this fix I can see the intended log message on my tomcat on JDK 17:
`13:30:03.993 ERROR {WrapperStartStopAppMain} [psiprobe.model.stats.StatsCollection] Stats desialization disabled, use '--add-opens java.base/java.util=ALL-UNNAMED' to start Tomcat to enable again
`
The complete stack trace of the NullPointerException is:
```
12:54:56.139 ERROR {WrapperStartStopAppMain} [o.s.web.context.ContextLoader] Context initialization …
```
=> NullPointerException fixed

psi-probe-core/src/main/java/psiprobe/AbstractTomcatContainer.java, psi-probe-core/src/main/java/psiprobe/tools/ApplicationUtils.java
- Remove support for tomcat 7, we already dropped tomcat 7 a long time ago.
- Remove support for tomcat 8 as end of life for long time and we also dropped that support long time ago.
- Remove support for earlier tomcat 8.5 or 9.0 versions as incredibly vulnerable in usage and no reason to support roughly 5 or more year old versions.
=> Remove legacy support of tomcat versions

psi-probe-core/src/main/java/psiprobe/tools/logging/catalina/CatalinaLoggerAccessor.java
getField isn't a true, false, null.  Its the field if it exists.  So this would be better served by simply checking not null to get true/false.
=> [fix] Catalina logger is wrong on timestamp

psi-probe-web/src/main/resources/stdout.properties
given no support for these, add them as typical naming
=> [logs] Add gc.log and localhost-access.log to stdout

pom.xml, psi-probe-core/src/main/java/psiprobe/controllers/datasources/ResetDataSourceController.java, psi-probe-web/src/main/webapp/WEB-INF/messages.properties, psi-probe-web/src/main/webapp/WEB-INF/messages_de.properties, psi-probe-web/src/main/webapp/WEB-INF/messages_es.properties, psi-probe-web/src/main/webapp/WEB-INF/messages_fr.properties, psi-probe-web/src/main/webapp/WEB-INF/messages_it.properties, psi-probe-web/src/main/webapp/WEB-INF/messages_ja.properties, psi-probe-web/src/main/webapp/WEB-INF/messages_ko.properties, psi-probe-web/src/main/webapp/WEB-INF/messages_pt_BR.properties, psi-probe-web/src/main/webapp/WEB-INF/messages_ru.properties, psi-probe-web/src/main/webapp/WEB-INF/messages_zh_CN.properties
its only rational reason to say c3p0 has to do with that one being only one setup to reset.  However, that is irrelevant in all regards because the message doesn't even talk about the specific datasource.
=> Require maven 3.9.2 and remove c3p0 from custom message that is generic in reality

psi-probe-core/src/main/java/psiprobe/beans/accessors/C3P0DatasourceAccessor.java, psi-probe-core/src/main/java/psiprobe/beans/accessors/DatasourceAccessor.java, psi-probe-core/src/main/java/psiprobe/beans/accessors/Dbcp2DatasourceAccessor.java, psi-probe-core/src/main/java/psiprobe/beans/accessors/HikariCpDatasourceAccessor.java, psi-probe-core/src/main/java/psiprobe/beans/accessors/OpenEjbBasicDatasourceAccessor.java, psi-probe-core/src/main/java/psiprobe/beans/accessors/OpenEjbManagedDatasourceAccessor.java, psi-probe-core/src/main/java/psiprobe/beans/accessors/OracleDatasourceAccessor.java, psi-probe-core/src/main/java/psiprobe/beans/accessors/OracleUcpDatasourceAccessor.java, psi-probe-core/src/main/java/psiprobe/beans/accessors/TomEeJdbcPoolDatasourceAccessor.java, psi-probe-core/src/main/java/psiprobe/beans/accessors/TomcatJdbcPoolDatasourceAccessor.java, psi-probe-core/src/main/java/psiprobe/beans/accessors/ViburCpDatasourceAccessor.java, psi-probe-tomcat10/src/main/java/psiprobe/beans/accessors/Tomcat10DbcpDatasourceAccessor.java, psi-probe-tomcat11/src/main/java/psiprobe/beans/accessors/Tomcat11DbcpDatasourceAccessor.java, psi-probe-tomcat85/src/main/java/psiprobe/beans/accessors/Tomcat85DbcpDatasourceAccessor.java, psi-probe-tomcat9/src/main/java/psiprobe/beans/accessors/Tomcat9DbcpDatasourceAccessor.java
- for few malformed exceptions, rethrow as SQL Exceptions with context they are malformed for the specific connection pooling.  Remainder were either never thrown or where otherwise SQLExceptions.
=> [datasources] Use SQLException instead of Exception

psi-probe-web/src/main/webapp/WEB-INF/messages_es.properties
with war plugin 3.4.0 this was breaking, turned out the encoding was incorrect and running switch on it fixed the issue.
=> [fix] For messages_es convert it from ansi encoding to utf-8 as expected

pom.xml, psi-probe-core/src/test/java/psiprobe/UtilsBaseTest.java, psi-probe-core/src/test/java/psiprobe/beans/accessors/OracleDatasourceAccessorTest.java, psi-probe-core/src/test/java/psiprobe/beans/accessors/OracleUcpDatasourceAccessorTest.java, psi-probe-core/src/test/java/psiprobe/model/DataSourceInfoTest.java
ojdbc logic for same is deprecated and deleted in 21c and above.  Since many still use 19c, leaving that be for now.  Both are provided and neither required to stay in sync.
=> junit 5 test cleanup and move ucp to 21.10.0.0

psi-probe-core/src/main/java/psiprobe/ProbeConfig.java, psi-probe-core/src/main/java/psiprobe/beans/accessors/OracleDatasourceAccessor.java
don't see that system properties override mode was documented nor used.  marking oracle pooling as deprecated as they deleted the code involved in 21c.  At the moment, still sitting on 19c for ojdbc datasource and 21c for ucp.  Cannot move ucp forwards until we delete current usage of ojdbc and/or review further.
=> Deprecate oracle pooling / Fixup deprecated spring property handling and drop system properties override mode

psi-probe-core/src/test/java/psiprobe/beans/accessors/Dbcp2DatasourceAccessorTest.java, psi-probe-core/src/test/java/psiprobe/beans/accessors/HikariCpDatasourceAccessorTest.java, psi-probe-core/src/test/java/psiprobe/beans/accessors/OpenEjbBasicDatasourceAccessorTest.java, psi-probe-core/src/test/java/psiprobe/beans/accessors/OpenEjbManagedDatasourceAccessorTest.java, psi-probe-core/src/test/java/psiprobe/beans/accessors/OracleDatasourceAccessorTest.java, psi-probe-core/src/test/java/psiprobe/beans/accessors/OracleUcpDatasourceAccessorTest.java, psi-probe-core/src/test/java/psiprobe/beans/accessors/TomcatJdbcPoolDatasourceAccessorTest.java, psi-probe-core/src/test/java/psiprobe/beans/accessors/ViburCpDatasourceAccessorTest.java
This makes it easier to drop c3p0 in near future as the intent of the change.
=> [tests] Stop using cp30 as a bad source / use hikari or vbur

pom.xml, psi-probe-core/pom.xml, psi-probe-web/pom.xml
- Make sure jcl over slf4j is excluded from sitemesh / displaytag right up front
- Remove all exclusions from displaytag in web module
- Change transaction api to provided
- Remove servlet api from the core module as only needed in web where tomcats not shown for same
- Exclude javaee-api from openejb
=> Cleanup library api usage

psi-probe-core/src/main/java/psiprobe/Utils.java, psi-probe-core/src/main/java/psiprobe/UtilsBase.java
we already determined this was of a type, no reason to pass original through wrapper logic, just pass that next value.
=> [cleanup] Cleanup scanner logic

psi-probe-core/src/main/java/psiprobe/Utils.java
The enumerate method is overloaded, it loads the array and returns count.  We don't need the count, just use the thread in enhanced array and process through it.
=> [cleanup] Use enhanced for loop to handle thread enumeration process

psi-probe-web/src/main/webapp/WEB-INF/jsp/certificates.jsp
Original logic to check empty from 4.0.0 release was wrong, fixed that but also removed it afterwards as it showing nothing was confusing but having it delegate to display tag to display 'Nothing found to display.' with proper headers around it looks better.
=> Certificates display changes

psi-probe-core/src/main/java/psiprobe/model/SessionSearchInfo.java
object is created as default then is cleared on setters or simply added to.  Its never null at any point.
=> [cleanup] Remove null checks that are impossible

psi-probe-core/src/main/java/psiprobe/controllers/deploy/UploadWarController.java
As i described in issue 1961, context is empty if you don't wait.
=> Issue 1961: Wait few seconds during upload to avoid empty context

pom.xml, psi-probe-core/src/main/java/psiprobe/controllers/AbstractTomcatContainerController.java, psi-probe-core/src/main/java/psiprobe/controllers/deploy/CopySingleFileController.java, psi-probe-core/src/main/java/psiprobe/controllers/deploy/UploadWarController.java, psi-probe-tomcat11/pom.xml, psi-probe-tomcat9/pom.xml
It seems tomcat backported changes to tomcat 9 that breaks same issue I faced with tomcat 10.1 usage.  I have hope pulling some of their code and confirming it still uploads might make jakarta a go.  Getting this merged then will retest.  If it works out, expect to release this again on javax then follow up a quick jakarta.  My hope anyways..
=> Update tomcat and rework upload logic

pom.xml
some cases this had issues, so just use target directly rather than trying to resolve from maven
=> [pom] Use target folder only for error prone ignore

psi-probe-core/src/main/java/psiprobe/beans/LogResolverBean.java, psi-probe-core/src/main/java/psiprobe/tools/logging/log4j2/Log4J2LoggerConfigAccessor.java
Currently Probe will not show log files in the log files window that are logged to through a Async appender. For example:
```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="INFO">
<Appenders>
<File name="MyFile" fileName="MyFile.log">
<PatternLayout pattern="%d{yyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"/>
</File>
<Async name="MyFileAsync">
<AppenderRef ref="MyFile"/>
</Async>
</Appenders>
<Loggers>
<Root level="debug">
<AppenderRef ref="MyFileAsync"/>
</Root>
</Loggers>
</Configuration>
```
This pull request will address this issue by unwrapping the async appenders' appenders, the logic for the unwrapping code is mostly copy & pasted from `LogbackLoggerAccessor#getSiftedAppenders` 
Fixes #4036
=> Support Log4J2 async appenders

psi-probe-core/src/main/java/psiprobe/controllers/certificates/ListCertificatesController.java, psi-probe-core/src/main/java/psiprobe/controllers/certificates/SslHostConfigHelper.java, psi-probe-core/src/main/java/psiprobe/model/Application.java, psi-probe-core/src/main/java/psiprobe/model/ServletInfo.java, psi-probe-core/src/main/java/psiprobe/tools/ApplicationUtils.java
currently tomcat 11 fails.  These changes get it so that tomcat 11 will start but only a blank page is shown.
The tomcat7 removal piece was simply found during this as long overdue for removal.
Tomcat 10 continues to work as expected with this change.
Thanks to @Teutron-flo for help via #4037 to get to this point successfully with the additional reflection here so that tomcat 10 support is not broken.
=> Known changes to better support tomcat 11

psi-probe-web/src/main/webapp/WEB-INF/jsp/showjsps.jsp
this was removed back in 2948f9267e3d31df487297e3ae82484f8fc4152a in 2016.  It was needed but surprising it took this long to even notice the issue.
=> Fix missing javascript on jsp page
