psi-probe/psi-probe

pom.xml
Owasp dependency check added to site page to scan library for
vulnerabilities.
=> Add basic report with owasp dependency NVD Checks

pom.xml, web/pom.xml
=> Add servlet-api and jsp-api dependencies to web project

core/src/main/java/com/googlecode/psiprobe/AwtAppContextClassloaderListener.java, web/src/main/webapp/WEB-INF/web.xml
=> Fix classloader Leak during JFreeChart initialization

core/src/main/java/com/googlecode/psiprobe/jsp/VisualScoreTag.java, core/src/test/java/com/googlecode/psiprobe/jsp/VisualScoreTagTest.java
=> Fixed #466 Missing gif

tomcat55adaptor/pom.xml
=> Fixes indirectly reference missing on Tomcat55ContainerAdaptor

core/pom.xml, core/src/main/java/com/googlecode/psiprobe/tools/SecurityUtils.java, pom.xml, web/src/main/webapp/WEB-INF/spring-probe-controllers.xml, web/src/main/webapp/WEB-INF/spring-probe-resources.xml, web/src/main/webapp/WEB-INF/spring-probe-security.xml, web/src/main/webapp/WEB-INF/spring-probe-servlet.xml, web/src/main/webapp/WEB-INF/spring-probe-stats.xml
Spring road to 4 needs a short pit stop in Spring 3 land.  spring-probe-resources.xml will need further review.  We have been running for a while now in production with this without issues.  Spring 4 is somewhat more complicated.  Once this has been thoroughly reviewed and any issues resolved, the work to spring 4 can start.
=> Spring3 Upgrade

tomcat70adaptor/src/main/java/com/googlecode/psiprobe/Tomcat70ContainerAdaptor.java, tomcat80adaptor/src/main/java/com/googlecode/psiprobe/Tomcat80ContainerAdaptor.java
Reverts psi-probe/psi-probe#546
=> Revert "Adding the support for Pivotal tc servers. "

core/pom.xml, pom.xml, tomcat70adapter/pom.xml, tomcat80adapter/pom.xml
Bring tomcat up to latest as well as fix the jsp plugin for tomcat 7 compilation to use tomcat7 as it was still targetting tomcat 5.
=> Tomcat updates

pom.xml
Maven Maintenance January 2016 - Fixes #576 
Monthly update of maven plugins and general cleanup within poms.
=> Maven Maintenance January 2016 - Fixes #576

core/pom.xml, pom.xml, tomcat70adapter/pom.xml, tomcat80adapter/pom.xml, web/pom.xml, web/src/main/webapp/WEB-INF/web.xml
Per http://tomcat.apache.org/whichversion.html
Update jsp, servlet, jstl, and add el to conform with tomcat 7 specification.
Update web.xml to servlet 3.0
=> Tomcat7 Servlet 3.0 Base

core/src/test/java/com/googlecode/psiprobe/beans/stats/listeners/FlapListenerTests.java, core/src/test/java/com/googlecode/psiprobe/beans/stats/listeners/ThresholdListenerTests.java
Some overrides were found to be missing in test code.  Added them.
=> Added missing @Overrides

.gitignore
=> Update gitignores to support hibernative annotation scanning - Fixes #589

core/src/main/java/com/googlecode/psiprobe/AbstractTomcatContainer.java, core/src/main/java/com/googlecode/psiprobe/controllers/jsp/RecompileJspController.java, core/src/main/java/com/googlecode/psiprobe/controllers/jsp/ViewSourceController.java, core/src/main/java/com/googlecode/psiprobe/controllers/sql/QueryHistoryItemController.java, core/src/main/java/com/googlecode/psiprobe/jsp/AddQueryParamTag.java, core/src/main/java/com/googlecode/psiprobe/jsp/ParamToggleTag.java, core/src/main/java/com/googlecode/psiprobe/tools/ApplicationUtils.java, core/src/main/java/com/googlecode/psiprobe/tools/MailMessage.java, core/src/main/java/com/googlecode/psiprobe/tools/Mailer.java, core/src/main/java/com/googlecode/psiprobe/tools/Whois.java, tomcat70adapter/src/main/java/com/googlecode/psiprobe/Tomcat70ContainerAdapter.java, tomcat80adapter/src/main/java/com/googlecode/psiprobe/Tomcat80ContainerAdapter.java, tomcat90adapter/src/main/java/com/googlecode/psiprobe/Tomcat90ContainerAdapter.java
Java Language Cleanup series.  Remove unnecessary casting.
=> Java Language Cleanups - Remove unnecessary Casting

core/src/main/java/com/googlecode/psiprobe/AwtAppContextClassloaderListener.java, core/src/main/java/com/googlecode/psiprobe/beans/stats/listeners/AbstractStatsCollectionListener.java, core/src/main/java/com/googlecode/psiprobe/controllers/DecoratorController.java, core/src/main/java/com/googlecode/psiprobe/controllers/deploy/UndeployContextController.java, core/src/main/java/com/googlecode/psiprobe/controllers/deploy/UploadWarController.java, core/src/main/java/com/googlecode/psiprobe/model/jsp/CompilerException.java, core/src/main/java/com/googlecode/psiprobe/model/jsp/Item.java, core/src/main/java/com/googlecode/psiprobe/model/wrapper/WrapperInfo.java, core/src/main/java/com/googlecode/psiprobe/tokenizer/Tokenizer.java, core/src/main/java/com/googlecode/psiprobe/tokenizer/TokenizerSymbol.java, core/src/main/java/com/googlecode/psiprobe/tools/ApplicationUtils.java, core/src/main/java/com/googlecode/psiprobe/tools/Instruments.java, core/src/main/java/com/googlecode/psiprobe/tools/Mailer.java, core/src/test/java/com/googlecode/psiprobe/jsp/VisualScoreTagTest.java
Add missing types
Format Cleanup
Use static final fields directly 
Comment empty constructor/method
Use parseInt instead of using valueOf
=> Java Language Cleanups - Micro Adjustments

web/src/main/webapp/WEB-INF/web.xml
Fixes #594 
Secure cookie will now be on by default.
=> [web.xml] Add session timeout and secure cookie attribute - Fixes #594

core/src/main/java/com/googlecode/psiprobe/jsp/VisualScoreTag.java, core/src/test/java/com/googlecode/psiprobe/jsp/VisualScoreTagTest.java
Fixes #618 VisualScoreTagTest problem with travis CI.
=> Fixes #618 VisualScoreTagTest problem with travis CI.

web/src/main/webapp/WEB-INF/classes/logback.xml
Fixes #627 Remove colon from log pattern
=> Fixes #627 Remove colon from log pattern

README.md, core/src/main/java/com/googlecode/psiprobe/controllers/TomcatAvailabilityController.java, core/src/main/java/com/googlecode/psiprobe/model/TomcatTestReport.java, core/src/main/java/com/googlecode/psiprobe/tools/AccessorFactory.java, core/src/main/java/com/googlecode/psiprobe/tools/MailMessage.java, core/src/main/java/com/googlecode/psiprobe/tools/SecurityUtils.java, core/src/main/java/com/googlecode/psiprobe/tools/url/UrlParser.java, core/src/test/java/com/googlecode/psiprobe/tools/MailMessageTest.java, core/src/test/java/com/googlecode/psiprobe/tools/url/UrlParserTest.java
This pull request is a thorough review of past weeks changes applying fixes as documented per conversations.  This consists of 7 commits but is rather small in nature.
=> Code Review Rework Fixes #617

core/src/main/java/psiprobe/tools/logging/logback/LogbackLoggerAccessor.java
Fixes #432 See issue for details of testing and research on issue.
=> Fix sift appender - Fixes #432

core/src/main/java/psiprobe/beans/LogResolverBean.java, core/src/main/java/psiprobe/beans/ResourceResolverBean.java
Applies #638 with squashed commits.
=> squid:S1193 - Exception types should not be tested using "instanceof" in catch blocks

core/src/main/java/psiprobe/AbstractTomcatContainer.java, core/src/main/java/psiprobe/AwtAppContextClassloaderListener.java, core/src/main/java/psiprobe/beans/ContainerWrapperBean.java, core/src/main/java/psiprobe/beans/LogResolverBean.java, core/src/main/java/psiprobe/beans/ResourceResolverBean.java, core/src/main/java/psiprobe/controllers/TomcatAvailabilityController.java, core/src/main/java/psiprobe/controllers/apps/AjaxReloadContextController.java, core/src/main/java/psiprobe/controllers/apps/AjaxToggleContextController.java, core/src/main/java/psiprobe/model/stats/StatsCollection.java, core/src/main/java/psiprobe/tools/AccessorFactory.java, core/src/main/java/psiprobe/tools/ApplicationUtils.java, core/src/main/java/psiprobe/tools/ReflectiveAccessor.java, core/src/main/java/psiprobe/tools/SimpleAccessor.java, core/src/main/java/psiprobe/tools/logging/DefaultAccessor.java, core/src/main/java/psiprobe/tools/logging/slf4jlogback/TomcatSlf4jLogbackLoggerAccessor.java
This covers majority of exceptions but still leaves quite a few caught Exception where there was more than one line of additonally processing in the exception.  For those, I sort of felt rather than duplicating code we can wait until we are on java 7 and can use multi-catch.
=> Cleanup exception handling per sonar results

core/src/main/java/psiprobe/controllers/truststore/TrustStoreController.java
Apply formatting rules - spaces intead of tabs, property type lists
=> Cleanup TrustStore Code to comply with our formatting rules

pom.xml
=> Add jdeps plugin to reporting section. 

web/src/main/webapp/js/prototype.js
Release notes
http://prototypejs.org/2015/09/24/prototype-1-7-3/v
=> Update prototype to 1.7.3

README.md, core/pom.xml, pom.xml, web/pom.xml, web/src/main/resources/logback.xml
Small build cleanup with no impact.
=> Build cleanup - no impact

.travis.yml, travis/after_success.sh
[travis] Adjust when to run coverage for pull requests
=> Travis CI changes to security for master

core/pom.xml, pom.xml
Zero impact to code or usage as these are provided and api's did not change
=> [pom] Update ojdbc to 12.1.0.2

core/src/main/java/psiprobe/controllers/deploy/CopySingleFileController.java, core/src/main/java/psiprobe/controllers/deploy/DeployController.java, web/src/main/webapp/WEB-INF/jsp/attributes.jsp, web/src/main/webapp/WEB-INF/jsp/deploy.jsp, web/src/main/webapp/WEB-INF/messages.properties, web/src/main/webapp/WEB-INF/messages_es.properties, web/src/main/webapp/WEB-INF/spring-probe-controllers.xml, web/src/main/webapp/css/classic/deploy.css
Issue #241. Allow users to copy a single file into a deployed context.
Usefull to hot change report, jsp, xml and properties files.
=> Issue #241. Allow users to copy a single file into a deployed context.

core/src/test/resources/spring/test-controllers.xml, web/src/main/webapp/WEB-INF/spring-probe-controllers.xml, web/src/main/webapp/WEB-INF/spring-probe-resources.xml, web/src/main/webapp/WEB-INF/spring-probe-security.xml, web/src/main/webapp/WEB-INF/spring-probe-servlet.xml, web/src/main/webapp/WEB-INF/spring-probe-stats.xml
=> [spring] Use xsd without version number so latest is used and avoids …fixes #727

core/src/main/java/psiprobe/controllers/RenderChartController.java
@jander99 / @MALfunction84 please review this one.  It doesn't seem to cause any issues but I'm not very familar with what this piece of code actually does.
=> Update deprecated jfreechart items

core/src/main/java/psiprobe/AbstractTomcatContainer.java, core/src/main/java/psiprobe/controllers/truststore/TrustStoreController.java
@MALfunction84 Need a review on this as I'm a bit unsure what actions outside of the keystore/truststore piece needs to be tested.  I was aware of the keystore/truststore leak as I experienced inability to delete a keystore after reading it but the other is more broad so not sure what I should check before assuming that is ok.
=> [leaks] Add try with resources to ensure resources are closed (found per sonarqube)

web/src/main/webapp/WEB-INF/spring-probe-stats.xml
Custom Quartz properties. Fixes #780
=> Custom Quartz properties. Fixes #780

core/src/main/java/psiprobe/controllers/jsp/DisplayJspController.java, web/src/main/webapp/WEB-INF/jsp/ajax/follow.jsp, web/src/main/webapp/WEB-INF/jsp/ajax/followed_file_info.jsp, web/src/main/webapp/WEB-INF/jsp/follow.jsp, web/src/main/webapp/WEB-INF/jsp/logs.jsp
This just ensures that if session is missing it doesn't attempt to create another.
=> [session] Turn off auto session creation on display jsp controller and missed jsp pages

core/pom.xml, core/src/main/java/psiprobe/beans/Dbcp2DatasourceAccessor.java, core/src/main/java/psiprobe/beans/TomcatJdbcPoolDatasourceAccessor.java, core/src/main/java/psiprobe/model/certificates/ConnectorInfo.java, pom.xml, web/src/main/webapp/WEB-INF/spring-probe-resources.xml
=> Add dbcp2 support and fix trivial bug - Closes #794

web/src/main/webapp/WEB-INF/jsp/decorators/probe.jsp, web/src/main/webapp/WEB-INF/messages_zh_CN.properties
=> add zh-cn lang

core/src/main/java/psiprobe/tools/ApplicationUtils.java
depending on tomcat version the return type was changed.  Technically speaking this is legacy servlet 2.4 code as it was for single thread check and there is no replacement as expected.  Tomcat internally changed how that method worked though as it was causing creation of instances if not already loaded for a class.  So this was fixed to return null when a class requested is not loaded.  So internally we are using reflection now and Null will simply be treated as false.  While that could be wrong based on context not being loaded, it's not really worth the effort given legacy here to make it smarter.
=> [utils] Fix for singleThreadModel as it might be Boolean or boolean

core/src/main/java/psiprobe/controllers/DecoratorController.java, core/src/main/java/psiprobe/controllers/help/HelpApplicationsController.java
This fixes #788 but may not entirely cover all issues as some things I don't have setup.  Also I did not want to take this fix and blindly apply to all.
=> [spring] Parameterizable "POST" Spring 4.3 Hack

core/src/main/java/psiprobe/beans/ContainerListenerBean.java
This is mainly for internal 172.x / 10.x addresses.  This patch should ensure it doesn't fail but rather just logs problem.  This is not the final solution but just a stop gap as this is looked at further.
=> [geo] Add try catch around geo call in case of address not found exception

core/pom.xml, pom.xml, rest/pom.xml, tomcat70adapter/pom.xml, tomcat80adapter/pom.xml, tomcat85adapter/pom.xml, tomcat90adapter/pom.xml, web/pom.xml
per maven team, we can go all https by turning off a value.  This is more of a test than anything else as prior to reaching out for help I had tried this on multiple repositories to no luck.  All the https entries are available but maven otherwise doesn't understand them yet.
=> [https] Use https throughout poms

pom.xml
=> [pom] Fix 'probe.version' - fixes #954

core/src/main/java/psiprobe/beans/ResourceResolverBean.java
#947 is a new feature request.  This fix allows for 'engine' names other than 'catalina' for global resource usage.
=> [tomcat] Support Engine naming beyond simply Catalina - Fixes #947

README.md
* - maven will show as error until we release
=> [readme] Add release badges *

pom.xml, web/src/main/webapp/WEB-INF/jsp/appsummary.jsp, web/src/main/webapp/WEB-INF/jsp/certificates.jsp, web/src/main/webapp/WEB-INF/jsp/datasources.jsp, web/src/main/webapp/WEB-INF/jsp/servlets.jsp, web/src/main/webapp/WEB-INF/messages.properties, web/src/main/webapp/WEB-INF/messages_de.properties, web/src/main/webapp/WEB-INF/messages_es.properties, web/src/main/webapp/WEB-INF/messages_fr.properties, web/src/main/webapp/WEB-INF/messages_it.properties, web/src/main/webapp/WEB-INF/messages_ja.properties, web/src/main/webapp/WEB-INF/messages_ko.properties, web/src/main/webapp/WEB-INF/messages_pt_BR.properties, web/src/main/webapp/WEB-INF/messages_ru.properties, web/src/main/webapp/WEB-INF/messages_zh_CN.properties
- correct spelling mistake
- switch jsp:include to c:import
- update copyright
- open famfamfam link in new page
=> Update jsp pages

core/src/main/java/psiprobe/beans/ContainerListenerBean.java
=> [geo] Add remoteAddrr not found patch - fixes #979

web/src/test/resources/logback-test.xml
=> Fixes #997

core/src/main/java/psiprobe/beans/LogResolverBean.java, core/src/main/java/psiprobe/tools/logging/log4j2/Log4J2AppenderAccessor.java, core/src/main/java/psiprobe/tools/logging/log4j2/Log4J2LoggerConfigAccessor.java, core/src/main/java/psiprobe/tools/logging/log4j2/Log4J2LoggerContextAccessor.java, core/src/main/java/psiprobe/tools/logging/log4j2/Log4J2WebLoggerContextUtilsAccessor.java
Run code formatter for log4j2 classes.
Signed-off-by: Jonathan Horowitz <jhorowitz@firedrum.com>
=> Fix live update of log4j2 log levels.

core/src/main/java/psiprobe/controllers/certificates/ListCertificatesController.java, core/src/main/java/psiprobe/model/certificates/OldConnectorInfo.java
Fixes #1000.
I don't know why Eclipse changed import orders...
=> [cert] Certificates tab works again in Tomcat 7/8. Fixes #1000

web/src/main/webapp/js/prototype.js
Part of this is actually already done in latest master of prototype but that is unreleased.  So patching it here.
=> [js] Patch eval use in prototype

core/src/main/java/psiprobe/ProbeConfig.java, core/src/main/java/psiprobe/beans/accessors/TomEEJdbcPoolDatasourceAccessor.java
This is my first experience with github, so I might not be doing this correctly.  I amended my commit since I forgot to add the second file.  
I can easily redo this.  Let me know if I should do something differently.
Thanks!
=> for issue 1097 

core/src/main/java/psiprobe/ProbeConfig.java, core/src/main/java/psiprobe/beans/accessors/OpenEjbBasicDatasourceAccessor.java, core/src/main/java/psiprobe/beans/accessors/TomEEJdbcPoolDatasourceAccessor.java
fixes issue #1097 
Thanks for your help.  I tried to follow what you said, but I'm pretty sure that I got something wrong.
I added the main repository as an upstream & did a hard reset & pulled from it.  The I added a few more changes for the TomEE dbcp2.  I ammended the commit.  I did something with a rebase to squash the 2 commits into 1, but I think that's where I got lost.  Sorry to be such a rookie ... i think that I squashed yesterday's change & today's change into one commit, pushed it, but when I create the pull request it says "Can’t automatically merge".   probably because I have a different change ID here since I squased them into 1. (so my repo doesn't have the unsquashed one?)
What's easiest for you?  Should I create a new ticket for this change set?  Sorry that I don't know …
=>  add tomee datasourceAccessor issue #1097  (#1098)

core/src/main/java/psiprobe/beans/ContainerListenerBean.java, core/src/main/java/psiprobe/controllers/connectors/ToggleConnectorStatusController.java, core/src/main/java/psiprobe/model/Connector.java, core/src/main/java/psiprobe/tools/JmxTools.java, web/src/main/webapp/WEB-INF/jsp/connectors.jsp
add status and start/stop operation in connector list, for convenient start/stop a connector in runtime.
=> add status and start/stop operation in connector list

core/src/main/java/psiprobe/AbstractTomcatContainer.java, core/src/main/java/psiprobe/beans/ResourceResolverBean.java, tomcat80adapter/src/main/java/psiprobe/Tomcat80ContainerAdapter.java, tomcat85adapter/src/main/java/psiprobe/Tomcat85ContainerAdapter.java, tomcat90adapter/src/main/java/psiprobe/Tomcat90ContainerAdapter.java
=> issue_1140

core/src/main/java/psiprobe/ProbeConfig.java
This can be called directly now
=> [deprecations] Upgrade spring WebMvcConfigurer

core/src/main/java/psiprobe/controllers/wrapper/RestartJvmController.java, core/src/main/java/psiprobe/controllers/wrapper/StopJvmController.java, core/src/main/java/psiprobe/controllers/wrapper/ThreadDumpController.java
Classes in wrapper package now extends from PostParametrizableViewController to support POST method.
=> Fixes issue #1275. 

core/src/main/java/psiprobe/beans/ResourceResolverBean.java
These occur frequently and provide little value other than excessive noise.
=> [ci] Lower some info messages to debug

core/src/test/java/psiprobe/ProbeConfigTest.java, core/src/test/resources/stdout.properties, core/src/test/webapp/WEB-INF/web.xml
This is basically a stub that needs filled out but a better starting point than most of the tests currently.
=> [tests] Start building out more

core/src/main/java/psiprobe/controllers/oshi/OshiController.java, pom.xml
underlying copy of oshi is now in sync with this use case making the port easier until it's determined how to place same code directly into oshi.
=> Upgrade oshi to 4.0.0

README.md
This is subject to change as all older support is actively being removed.  Base revisions are going to go up.
=> [ci] Add our supported revisions to README

pom.xml, psi-probe-tomcat7/pom.xml, psi-probe-tomcat85/pom.xml, psi-probe-tomcat9/pom.xml
=> [pom] Update tomcats

psi-probe-web/src/main/webapp/WEB-INF/jsp/zoomreq.jsp, psi-probe-web/src/main/webapp/js/func.js
Fix the bug that the connector chart cannot slide to the maximum value, and fix the bug that the chart size cannot be changed by clicking the slider
=> Fix the bug that the connector chart cannot slide to the maximum value, and fix the bug that the chart size cannot be changed by clicking the slider

pom.xml, psi-probe-tomcat10/pom.xml, psi-probe-tomcat85/pom.xml, psi-probe-tomcat9/pom.xml
=> [pom] Update tomcat versions to latest

pom.xml, psi-probe-core/pom.xml
continuation of the 2 line as used here.
=> Move sitemesh from 'opensymphony' to my ownership 'com.github.hazendaz' as version 2.5.1

pom.xml
Porting actual code back to this repo immediately after this commit point
=> [pom] Bump probe ojdbc to 3.1.9

psi-probe-core/src/main/java/psiprobe/AbstractTomcatContainer.java, psi-probe-core/src/main/java/psiprobe/TomcatContainer.java, psi-probe-core/src/main/java/psiprobe/controllers/deploy/UploadWarController.java
was even stating it was a jar.  was not used.
=> [cleanup] Remove unused URL for upload war

psi-probe-core/src/main/java/psiprobe/beans/ContainerWrapperBean.java, psi-probe-core/src/main/java/psiprobe/beans/accessors/TomcatJdbcPoolDatasourceAccessor.java
Fixes #815 
The original thread appears we were asking for requester to add this.  That never happened.  At some point it was added for ojdbc, so adding it now.
=> Fix exception usage and add XADataSource for tomcat-jdbc

psi-probe-core/src/main/java/psiprobe/beans/ClusterWrapperBean.java, psi-probe-core/src/main/java/psiprobe/beans/ContainerListenerBean.java, psi-probe-core/src/main/java/psiprobe/beans/JvmMemoryInfoAccessorBean.java, psi-probe-core/src/main/java/psiprobe/beans/RuntimeInfoAccessorBean.java, psi-probe-core/src/main/java/psiprobe/controllers/threads/ListSunThreadsController.java, psi-probe-core/src/main/java/psiprobe/controllers/threads/ThreadStackController.java, psi-probe-core/src/main/java/psiprobe/tools/JmxTools.java
Prior logic extensively threw all over the place exceptions at (Exception).  Now handling as much as possible internally with only some basic leaks out.  This further makes code more manageable and does a better job at logging actual condition that is a problem.  Further, due to some of the extensive try/catch used previously there is likely possibility of more data retrieval now.
=> [jmx] Better handling of exceptions on proper types

psi-probe-core/src/main/java/psiprobe/ProbeSecurityConfig.java
jsp page check which needs session was broken.  This fixes #2907
=> Fix spring security bug introduced in release 4.0.0 that stopped creating sessions - fixes #2907

.gitignore, psi-probe-core/pom.xml, psi-probe-core/src/main/java/psiprobe/controllers/deploy/CopySingleFileController.java, psi-probe-core/src/main/java/psiprobe/controllers/deploy/UploadWarController.java, psi-probe-rest/pom.xml, psi-probe-tomcat10/pom.xml, psi-probe-tomcat11/pom.xml
=> [fix] Correct import issue as reported on issue #2982

README.md
Add precondition concerning --add-opens to README.md for issue 3134
=> Issue 3134: Add precondition concerning --add-opens

psi-probe-core/src/main/java/psiprobe/jsp/ParamToggleTag.java, psi-probe-web/src/main/webapp/WEB-INF/jsp/appsummary.jsp
1. Setting size param in toggle tag at the end
2. Certain links (including ajax-calls) in appsummary.jsp have size parameter, now
=> Issue 3154: Fixed size param position in requests

psi-probe-core/src/main/java/psiprobe/AbstractTomcatContainer.java
=> Fix #1359 per suggested user testing - better handling of war names with # usage
